### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by Samvdg** [lemasato/Steam-Account-Switcher#12]
This is not a drastic issue or antyhing, though i am a developer myself but sadly am not experienced yet with python.
i have a couple of questions surrounding the safety of my accounts while using this application.

1. Does your application require an internet connection at any given point? (outside of updates)
2. How do i know you're not just gonna run off with my account information?
3. Can you actually guarantee me that you did not develop this with bad intent

It's not like i don't WANT to trust you, i just have trust issues

**Comment by lemasato** [comment]
Hiya, this is not Python but AutoHotKey.
This tool should not require any internet connection beside updating. For example, if you intend on running Steam in offline mode or in an offline environment, SAS will work just fine. On top of that, your credentials are never saved by SAS. Your password is never required, we are only taking advantage of Steam 'cookies' system.

Same principle with BattleNET Account Switcher. Only taking advantage of their cookies system to force logging into a previously saved account. This is why these tools only work if you tick "Remember Password" as otherwise the 'cookie' will never be created by Steam/BNet.
