### ISSUE TITLE
2 Steamaccounts in 2 Steamfolders

### ISSUE THREAD

**Issue by o0Julia0o** [lemasato/Steam-Account-Switcher#3]
the tool only works with 1 steamfolder. But i need to switch 2 accounts with 2 different steamfolders.

**Comment by lemasato** [comment]
Will be part of next update, as the /SteamFolder parameter. Usage example:
```
Steam Account Switcher.exe /SteamFolder="C:\Games\Steam"
```
Will be using Steam.exe from the `C:\Games\Steam` folder.

**Comment by lemasato** [comment]
@o0Julia0o Could you give me an usage example?
So that I could make sure I understand correctly how it would work, and debug if needed.

Also decided to replace the parameter to /SteamPath instead, as well as adding some features. The /SteamPath parameter can work with:
- Only the Steam folder. In this case, the executable will be the default Steam.exe
eg: `/SteamPath="C:\Program Files (x86)\Steam"`
- The full exe path, in case you want to use a specific executable
eg: `/SteamPath="C:\Program Files (x86)\Steam\Steam.exe"`
It also works with parameters.
eg: `/SteamPath="C:\Program Files (x86)\Steam\Steam.exe -dosomething -someparameter"`

Would this suit your needs?

**Comment by o0Julia0o** [comment]
Thx. I have 2 Steamfolders:
1. G:\Steam  -> User: Julia
2. G:\Steam2 -> User: Pascal

We wan´t to keep them and their games, etc. apart. But it´s boring always to do the login. That´s where you tool can maybe do the work.

We are looking for a 1cklick-Tool which can do the login for us. So we just have to start a shortcut and the correct Steam starts with the coreect user logged in.

So we have 2 shortcuts:
1. G:\Steam User: Julia
2. G:\Steam2 User: Pascal

**Comment by lemasato** [comment]
Sorry I kind of forgot to push the changes as an official update. I hope you used the changes from the master branch, or found an alternative solution since then.
Now part of the [0.2.2 update](https://github.com/lemasato/steam-account-switcher/releases)

**Comment by o0Julia0o** [comment]
Nice - thx!
