### ISSUE TITLE
I already installed .NET Core, but it says I still need to install it.

### ISSUE THREAD

**Issue by raisedheart** [lemasato/Steam-Account-Switcher#7]
I already have the latest recommended version of .NET Core installed, however, it claims I don't have it. I tried repairing it and it didn't fix the issue. I tried installing the latest version and it still isn't working. I also tried uninstalling .NET Core. Any suggestions on what to do?

**Comment by lemasato** [comment]
Hi,
Someone on the discord server ran into a similar issue, to which I suggested to install a package like this one https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/ and I suppose that fixed it.

**Comment by raisedheart** [comment]
I installed the package and restarted my computer and it sadly didn't fix it.

**Comment by lemasato** [comment]
Could you provide screenshots of the message box?  
The only other thing I could recommend would be to use the AHK instead of the executable ([Steam-Account-Switcher-AHK-v0-2-1.zip](https://github.com/lemasato/Steam-Account-Switcher/releases/download/0.2.1/Steam-Account-Switcher-AHK-v0-2-1.zip)). You simply need [AutoHotKey](https://www.autohotkey.com/download/ahk-install.exe) installed.

**Comment by raisedheart** [comment]
![image](https://user-images.githubusercontent.com/51804818/79057428-2dab6f00-7c27-11ea-8bfe-270312be7a98.png)
Here's a screenshot. I appreciate the effort, I think I'll use the AHK version.
