### ISSUE TITLE
Bug with Game

### ISSUE THREAD

**Issue by slaver4545** [lemasato/Steam-Account-Switcher#8]
For some reason whenever I sign into steam using the account switcher and I launch a game I can't use any macro's on my Logitech G Pro and any rebinded keys on the mouse don't work within the game. When I sign out and sign back in normally the game and mouse works perfectly fine. I'm just wondering is there a simple fix to this or no?

**Comment by lemasato** [comment]
Hi,
I believe this could be caused by the admin mode.
Using the /SkipAdmin cmd-line parameter will allow you to use Steam Account Switcher without running it as admin. This can be done by creating a shortcut, right click > properties, and adding /SkipAdmin at the end of the full exe location like so: 
`"C:\Users\Masato\Desktop\Steam-Account-Switcher.exe"` becomes `"C:\Users\Masato\Desktop\Steam-Account-Switcher.exe" /SkipAdmin`

**Comment by slaver4545** [comment]
Thanks man works perfectly now. Really great program by the way
